### ISSUE TITLE
broken on windows

### ISSUE THREAD

**Issue by ryuukk** [BindBC/bindbc-sdl#50] opened 2023-03-12 02:51 UTC
discussion: https://forum.dlang.org/thread/gbsyqfjhqhqiguqshxso@forum.dlang.org

With dmd:

```
$ dub run
    Fetching bindbc-loader 1.0.3 (getting selected version)
    Fetching bindbc-sdl 1.3.1 (getting selected version)
    Starting Performing "debug" build using C:\D\dmd2\windows\bin\dmd.exe for x86_64.
    Building bindbc-loader 1.0.3: building configuration [noBC]
    Building bindbc-sdl 1.3.1: building configuration [dynamic]
C:\Users\ryuukk\AppData\Local\dub\packages\bindbc-sdl-1.3.1\bindbc-sdl\source\bindbc\sdl\ctypes.c(8): fatal error C1034: stddef.h: no include path set
C:\Users\ryuukk\AppData\Local\dub\packages\bindbc-sdl-1.3.1\bindbc-sdl\source\bindbc\sdl\config.d(127,16): Error: C preprocess command C:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.34.31933\bin\HostX64\x64\cl.exe failed for file C:\Users\ryuukk\AppData\Local\dub\packages\bindbc-sdl-1.3.1\bindbc-sdl\source\bindbc\sdl\ctypes.c, exit status 2

Error C:\D\dmd2\windows\bin\dmd.exe failed with exit code 1.
```

With command line for developpers since you seem to be using ImportC

```
    Starting Performing "debug" build using C:\D\dmd2\windows\bin\dmd.exe for x86_64.
  Up-to-date bindbc-loader 1.0.3: target for configuration [noBC] is up to date.
    Building bindbc-sdl 1.3.1: building configuration [dynamic]
C:\Users\ryuukk\AppData\Local\dub\packages\bindbc-sdl-1.3.1\bindbc-sdl\source\sdl\rwops.d(44,9): Warning: statement is not reachable
C:\Users\ryuukk\AppData\Local\dub\packages\bindbc-sdl-1.3.1\bindbc-sdl\source\bindbc\sdl\package.d(26,26): Deprecation: enum member `bindbc.sdl.config.SDLSupport.sdl209` is deprecated - Please use `v2_0_9` instead
Error: warnings are treated as errors
       Use -wi if you wish to treat warnings only as informational.
Error C:\D\dmd2\windows\bin\dmd.exe failed with exit code 1.

```

And with ldc

```
    Starting Performing "debug" build using ldc2 for x86_64.
    Building bindbc-loader 1.0.3: building configuration [noBC]
    Building bindbc-sdl 1.3.1: building configuration [dynamic]
C:\Users\ryuukk\AppData\Local\dub\packages\bindbc-sdl-1.3.1\bindbc-sdl\source\bindbc\sdl\ctypes.c(8,1): Error: C preprocessor directive `#include` is not supported
C:\Users\ryuukk\AppData\Local\dub\packages\bindbc-sdl-1.3.1\bindbc-sdl\source\bindbc\sdl\ctypes.c(8,1): Error: no type for declarator before `#`
C:\Users\ryuukk\AppData\Local\dub\packages\bindbc-sdl-1.3.1\bindbc-sdl\source\bindbc\sdl\ctypes.c(9,1): Error: C preprocessor directive `#include` is not supported
C:\Users\ryuukk\AppData\Local\dub\packages\bindbc-sdl-1.3.1\bindbc-sdl\source\bindbc\sdl\config.d(127,16): Error: module `ctypes` import `c_long` not found, did you mean alias `ctypes.c_ulong`?
Error: undefined identifier `wchar_t`, did you mean alias `c_wchar_t`?
Error: undefined identifier `va_list`, did you mean alias `c_va_list`?
C:\Users\ryuukk\AppData\Local\dub\packages\bindbc-sdl-1.3.1\bindbc-sdl\source\sdl\rwops.d(44,9): Warning: statement is not reachable
C:\Users\ryuukk\AppData\Local\dub\packages\bindbc-sdl-1.3.1\bindbc-sdl\source\bindbc\sdl\package.d(26,26): Deprecation: enum member `bindbc.sdl.config.SDLSupport.sdl209` is deprecated - Please use `v2_0_9` instead
Error ldc2 failed with exit code 1.

```

Dub file:

```json
{
	"authors": [
		"ryuukk"
	],
	"copyright": "Copyright © 2023, ryuukk",
	"description": "A minimal D application.",
	"license": "proprietary",
	"name": "hellosdl",
	"dependencies": {
		"bindbc-sdl": "~>1.3.0",
	},
	"versions": [
		"SDL_2_26"
	],
}
```

code: 

```D
import bindbc.sdl;
import core.stdc.stdio;

void main(){

	// here we load the dll
	auto ret = loadSDL();

	// here handle cases where it failed to load the dll
	if(ret != sdlSupport){
		if(ret == SDLSupport.noLibrary){
			// dll not found
		}else if(ret == SDLSupport.badLibrary){
			// wrong DLL, perhaps 32bit vs 64bit?
		}
		return;
	}

	// all good, let's use SDL


	SDL_Window* window = NULL;
	SDL_Surface* screenSurface = NULL;
	if (SDL_Init(SDL_INIT_VIDEO) < 0) {
	  fprintf(stderr, "could not initialize sdl2: %s\n", SDL_GetError());
	  return 1;
	}
	window = SDL_CreateWindow(
				    "hello_sdl2",
				    SDL_WINDOWPOS_UNDEFINED, SDL_WINDOWPOS_UNDEFINED,
				    SCREEN_WIDTH, SCREEN_HEIGHT,
				    SDL_WINDOW_SHOWN
				    );
	if (window == null) {
	  fprintf(stderr, "could not create window: %s\n", SDL_GetError());
	  return 1;
	}
	screenSurface = SDL_GetWindowSurface(window);
	SDL_FillRect(screenSurface, null, SDL_MapRGB(screenSurface->format, 0xFF, 0xFF, 0xFF));
	SDL_UpdateWindowSurface(window);
	SDL_Delay(2000);
	SDL_DestroyWindow(window);
	SDL_Quit();
}
```

Last version working: 1.2.4

I suggest making the experience as smooth as possible since SDL is quite popular and people expect things to be working out of the box

**Comment by rikkimax** [comment] 2023-03-12 02:58
Appears that there is a stray c file in the source directory (which would certainly explain it).

https://github.com/BindBC/bindbc-sdl/blob/master/source/bindbc/sdl/ctypes.c

**Comment by ichordev** [comment] 2023-03-12 04:23
What versions are these compilers and what __VERSION__ do they report?

**Comment by rikkimax** [comment] 2023-03-12 04:43
It'll be within the last major release I expect. ImportC support in dub was turned on pretty recently.

Remove the stray file, tag and everything should work again for those without the system toolchain installed.

**Comment by ichordev** [comment] 2023-03-12 05:45
> It'll be within the last major release I expect.

2.101.1 won't compile `NULL` or `->`, or allow `return 1;` from `void main()`.
If those errors are corrected, the provided code works just fine. However, I did modify the code to achieve this result, so I'd definitely want to know how @ryuukk was able to compile this code to try and replicate the issue.

Also how come it's compiling parts of BindBC-SDL that the test project doesn't use in these error messages you've sent?

**Comment by rikkimax** [comment] 2023-03-12 05:57
Ohhhhhh you actually intended to use the experimental feature that is ImportC.

Yeah it won't work if you don't have the system toolchain installed. You need it for the preprocessor, we don't ship it and a lot of D developers don't install it on Windows.

Use these instead:

https://github.com/dlang/dmd/blob/master/druntime/src/core/stdc/config.d
https://github.com/dlang/dmd/blob/master/druntime/src/core/stdc/stddef.d
https://github.com/dlang/dmd/blob/master/druntime/src/core/stdc/stdarg.d

**Comment by ichordev** [comment] 2023-03-12 11:31
> Use these instead:
> 
> https://github.com/dlang/dmd/blob/master/druntime/src/core/stdc/config.d https://github.com/dlang/dmd/blob/master/druntime/src/core/stdc/stddef.d https://github.com/dlang/dmd/blob/master/druntime/src/core/stdc/stdarg.d

https://github.com/BindBC/bindbc-sdl/pull/25

Can add a `SDL_NoImportC` if that works for you.

**Comment by schveiguy** [comment] 2023-03-13 15:41
FWIW, ImportC should NOT be relied upon for major libraries. It's both unstable and not fully supported across all the compilers.

I would recommend if you do want to include ImportC that you put the C file in another source directory only active with a separate config, as just having a C file in your project can hijack other imports (one of the problems in-flux with current ImportC) for compilers that have ImportC enabled.

**Comment by ichordev** [comment] 2023-03-14 02:32
It isn’t a preview feature, so I expect it to work properly.

There’s not much I can do in the next couple of days. In the meantime, if someone would like to PR with a few more platforms here that would be a big help: [config.d](https://github.com/BindBC/bindbc-sdl/blob/master/source/bindbc/sdl/config.d#L134)

**Comment by ichordev** [comment] 2023-03-14 21:56
Again, this is the reason: https://github.com/BindBC/bindbc-sdl/pull/25

**Comment by schveiguy** [comment] 2023-03-15 01:02
Correct me if I'm wrong, but doesn't webassembly require LDC anyway? And LDC doesn't support ImportC (yet)?

The solution is to define `c_long` as it was in the PR. I found it reasonable.

**Comment by ichordev** [comment] 2023-03-15 03:26
> It should have been a preview feature, but @WalterBright added it without a preview switch. The implied "officialness" of it based on it not having a preview switch is misplaced. It for sure is NOT a finished or stable feature.

I’ve just finished travelling finally.
I had no idea it would be such a big issue. D needs to work on its over-promising new features that simply *aren’t finished*, it’s going to cause this to happen again and again.
I’ve always have a C compiler installed when using this library (e.g. to build SDL, because every PM seems to carry outdated SDL builds?) so a system with dmd but no C compiler never crossed my mind. I’m sorry about all the trouble it’s caused, I was completely oblivious to Import C being so unfinished.

I appreciate the PR @ryuukk but I think I’ll just research the types to add a few more statements aliases, and then cut out ImportC entirely. I can see it’s not worth the hassle, I’ve tried going through this hell with other experimental D features. *Especially* since some versions of dub seem to randomly try to compile the .c file even when it’s not included in anything!
Hopefully it’ll be fixed by the end of the day. Sorry about all this mess. 🙇‍♀️

**Comment by rikkimax** [comment] 2023-03-15 03:37
Walter announced it without it even supporting the preprocessor... yeah the communication around it hasn't been good from the start.

Dub supports ImportC. If it's in your sourcePath it'll add it just like any other D file. This was done by those who actually do want to use it.

**Closed** 2023-03-15 07:23 UTC

**Comment by WalterBright** [comment] 2023-03-15 07:42
ImportC has supported the C preprocessor for some time now.

If there's a .c file with the same name as a .d file, and the .c file is earlier in the import search path, the .c file will be found first and then compiled with the ImportC compiler. Is this the issue here?

**Comment by rikkimax** [comment] 2023-03-15 07:47
> Is this the issue here?

No.

https://github.com/BindBC/bindbc-sdl/commit/99444c7fd8bcaa57b996a56d1ec25647c63f29fb#diff-105382861214c8a51e89b493166b55ec3ec8beb7d5d048ce9e4092d1c3a1b357L130

ImportC was being used on a computer without a C compiler.

**Comment by WalterBright** [comment] 2023-03-15 08:44
So there was a stray .c file on a computer without a C compiler? I'm still not getting what the issue is. (ImportC will try to compile a .c file regardless of if a C compiler was on the computer or not.)

**Comment by rikkimax** [comment] 2023-03-15 08:50
It was intended.

Indeed it did try to compile it.

> C:\Users\ryuukk\AppData\Local\dub\packages\bindbc-sdl-1.3.1\bindbc-sdl\source\bindbc\sdl\ctypes.c(8): fatal error C1034: stddef.h: no include path set
C:\Users\ryuukk\AppData\Local\dub\packages\bindbc-sdl-1.3.1\bindbc-sdl\source\bindbc\sdl\config.d(127,16): Error: C preprocess command C:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.34.31933\bin\HostX64\x64\cl.exe failed for file C:\Users\ryuukk\AppData\Local\dub\packages\bindbc-sdl-1.3.1\bindbc-sdl\source\bindbc\sdl\ctypes.c, exit status 2

Here is the output that came from the N.G. report (that triggered all this):

> failed launching cl.exe /P /Zc:preprocessor /PD /nologo C:\Users\idoug\AppData\Local\dub\packages\bindbc-sdl-1.3.0\bindbc-sdl\source\bindbc\sdl\ctypes.c /FIC:\D\dmd2\windows\bin64\..\..\src\druntime\import\importc.h /Fictypes.i
> C:\Users\idoug\AppData\Local\dub\packages\bindbc-sdl-1.3.0\bindbc-sdl\source\bindbc\sdl\config.d(127,16): Error: C preprocess command cl.exe failed for file C:\Users\idoug\AppData\Local\dub\packages\bindbc-sdl-1.3.0\bindbc-sdl\source\bindbc\sdl\ctypes.c, exit status 1

There could be multiple issues at play here.

**Comment by WalterBright** [comment] 2023-03-15 08:53
What was intended?

What it did was try to launch the C preprocessor for Windows, which is run by Microsoft's CL program. ImportC does not have its own preprocessor.

**Comment by rikkimax** [comment] 2023-03-15 08:59
ImportC was intended to be used here.

Problem is, not everyone is a native developer with the system toolchain (MSVC) installed.

This is a bit of a problem if you are new to the language and want to use a feature (unintentionally via a dependency) that depends on something we don't ship.

It's not really appropriate to use ImportC for dynamic bindings like this one for the above reason (currently). Once we figure out a solution for which we ship a preprocessor + headers then maybe we can recommend it.

However that C1034 does sound like a problem.

**Comment by WalterBright** [comment] 2023-03-15 09:08
I still don't get it. If the project includes a .c file, and the .c file needs to be compiled into the project, and the target system does not have a C compiler, it's going to fail with or without ImportC.

The reason ImportC relies on the associated C compiler's preprocessor is all those preprocessors predefine several hundred macros, most of which are undocumented, and they vary from version to version and from compiler switch to compiler switch.

Some more points:

1. Microsoft C has a free version which can be downloaded.
2. If you craft a C file that does not require use of the preprocessor, rename it to `.i` and no attempt will be made to run the preprocessor
3. You can include the dmpp preprocessor (it's Boost licensed) https://github.com/DigitalMars/dmpp

**Comment by rikkimax** [comment] 2023-03-15 09:18
The .c file didn't need to exist. Everything it did is available in druntime as alias's. https://github.com/BindBC/bindbc-sdl/commit/99444c7fd8bcaa57b996a56d1ec25647c63f29fb#diff-4cba12e7870b048bf9c97e67b15670a2c5df3fc42d8f4d35341dabcc8d0db852

Basically, ImportC was the wrong tool for the job. It wasn't needed, it only introduced failure modes (like missing preprocessor).

But there may still be issues with ImportC that it shows off (C1034), they are simply unrelated to what this project needs to deal with.

**Comment by rikkimax** [comment] 2023-03-15 14:11
GDC has a pretty long lead time between what is in dmd and what is available in repos. It's gonna be a while before people can safely use ImportC in OSS'd projects like this one even once problems in dmd such as distribution of a cpp & headers with it (seems to be possible with clang + MinGW + ucrt, got it working! Documented on Discord #langdev channel).

**Comment by WalterBright** [comment] 2023-03-15 15:59
@ryuukk (While you are here, invoking dmd directly on a C file can also not work, even when using the native command line prompt https://issues.dlang.org/show_bug.cgi?id=23757)

I cannot fix that without knowing what the .h file is doing, and I don't have that .h file. The bug report needs to show the specific lines in the .h file that elicit that error message. Thanks!
